### ISSUE TITLE
Doubled Readme Page Opening

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#2279]
**Describe the bug**

When you begin installation of a modlist, the readme page is opened twice - two tabs are opened for the same page. On finishing installation, the readme page is opened only once. The latter seems correct and the former should only open the readme page once.

**Additional Context**

Windows 11

**Wabbajack Version**

3.0.0.5

**Logs**

![image](https://user-images.githubusercontent.com/25124348/213572461-58c01c8e-127a-433b-abbb-e58af4661b02.png)

**Comment by ForgottenGlory** [comment]
https://user-images.githubusercontent.com/25124348/213573542-46566843-1858-4b06-bfbc-4f8f026027fd.mp4

Video of it happening just in case

**Comment by EzioTheDeadPoet** [comment]
This bug is still present.
Can confirm it happening when using the install from disk option.

**Comment by TRIPSLORD** [comment]
Can we get an option to turn off auto opening of the readme? I can just open it myself if I want to

**Comment by EzioTheDeadPoet** [comment]
no--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 3/2/23, 18:32 TRIPSLORD ***@***.***> wrote:

   
  Can we get an option to turn off auto opening of the readme? I can just open it myself if I want to

**Comment by TRIPSLORD** [comment]
> no--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 3/2/23, 18:32 TRIPSLORD ***@***.***> wrote: Can we get an option to turn off auto opening of the readme? I can just open it myself if I want to —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Why not

**Comment by EzioTheDeadPoet** [comment]
Because seeing and actually reading the readmes aren't optional steps. And we won't add features that even remotely entertain the idea that they could be optional.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 3/3/23, 23:10 TRIPSLORD ***@***.***> wrote:

   
   
   no--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 3/2/23, 18:32 TRIPSLORD @.> wrote: Can we get an option to turn off auto opening of the readme? I can just open it myself if I want to —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 
   
  Why not

**Comment by ClarSco** [comment]
Maybe a better approach to auto opening the README would be to insert a page in WJ that precedes the the Install Configuration page that prompts the user to open the README and follow any pre-installation steps listed there, and similarly, a page for post-installation steps, once WJ has done it's job.

At the moment, there is nothing telling a user **WHY** their browser has just decided to load up the README, which means that users are far more likely to simply close it without actually reading it.

**Comment by TRIPSLORD** [comment]
> Because seeing and actually reading the readmes aren't optional steps. And we won't add features that even remotely entertain the idea that they could be optional.
If a user doesn't read the readme that's on them, just stop spamming my browser please

**Comment by EzioTheDeadPoet** [comment]
fixed in #2325

**Comment by Lartza** [comment]
Still an issue in 3.1.0.0

**Comment by FF7CloudsNobody** [comment]
I can also confirm that the issue is still present. Could it be due to having 2 "OpenWebsite... Readme" methods that are located on line 124 of ModListVM.cs and 334 of InstallerVM.cs?

**Comment by FF7CloudsNobody** [comment]
Why not have it as a reaction to clicking the install button on the main page instead of a delayed load after going to the install page? Just have wabbajack pre-load the urls on boot and only use them if the install modlist button is clicked
